# Generated by Django 5.2.7 on 2025-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='target_audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
